name: Azure Container Apps Replica

on:
  workflow_dispatch:
    inputs:
      appname:
        required: true
        description: "AppName"
        type: string
      rgname:
        required: true
        description: "Resource Group"
        type: string
      minreplica:
        required: true
        description: "Minimum Replica"
        type: string
      maxreplica:
        required: true
        description: "Maximum Replica"
        type: string

permissions:
      id-token: write
      contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Restart ContainerApp with revision ${{ github.event.inputs.revname }}
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az containerapp update -n ${{ github.event.inputs.appname }} -g ${{ github.event.inputs.rgname }} --min-replicas ${{ github.event.inputs.minreplica }} --max-replicas ${{ github.event.inputs.maxreplica }}
